export const ActionType = {
	FETCH_COUNTRY_BEGIN: 'FETCH_COUNTRY_BEGIN',
	FETCH_COUNTRY_SUCCESS: 'FETCH_COUNTRY_SUCCESS',
	FETCH_COUNTRY_FAILED: 'FETCH_COUNTRY_FAILED',
	FETCH_CITY_BEGIN: 'FETCH_CITY_BEGIN',
	FETCH_CITY_SUCCESS: 'FETCH_CITY_SUCCESS',
	FETCH_CITY_FAILED: 'FETCH_CITY_FAILED',
	FETCH_MEASUREMENT_BEGIN: 'FETCH_MEASUREMENT_BEGIN',
	FETCH_MEASUREMENT_SUCCESS: 'FETCH_MEASUREMENT_SUCCESS',
	FETCH_MEASUREMENT_FAILED: 'FETCH_MEASUREMENT_FAILED',
};
